. "$HOME/.cargo/env"
PATH=$HOME/bin:/usr/local/bin:$HOME/anaconda3/bin:$PATH
PATH=$HOME/Applications:$PATH
PATH=/opt/platform-tools:$PATH
PATH=/home/sandesh/.local/bin:$PATH
PATH=/home/sandesh/go/bin:$PATH
export PATH
