#! /bin/sh
# Rosé pine 
bspc config focused_border_color "#6e6a86"

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          5 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^3'
bspc rule -a Alacritty desktop='^2'
bspc rule -a discord desktop='^4'
bspc rule -a Zathura desktop='^1' state=tiled
bspc rule -a thunderbird desktop='^1' 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

foatingapps=('Lxappearance' 'Pavucontrol' 'Blueberry.py' 'Nitrogen')

for app in "${foatingapps[@]}"
do 
    bspc rule -a $app state=floating
done
$HOME/.config/polybar/launch.sh &
xinput set-prop "ELAN050A:01 04F3:3158 Touchpad" "libinput Tapping Enabled" 1
#nitrogen --restore &
feh --bg-fill ~/.config/feh/wallpapers/base.jpg
pgrep bspswallow || ~/bin/bspswallow &
picom &
lxsession &
xsetroot -cursor_name left_ptr
nm-applet &
blueberry-tray

