#!/usr/bin/env bash
export GSETTINGS_SCHEMA_DIR="$HOME/.local/share/gnome-shell/extensions/just-perfection-desktop@just-perfection/schemas"
current=$(gsettings get org.gnome.shell.extensions.just-perfection panel)
if [ "$current" = "true" ]; then
  gsettings set org.gnome.shell.extensions.just-perfection panel false
else
  gsettings set org.gnome.shell.extensions.just-perfection panel true
fi
