PROMPT="%F{38}[%f%F{222}%~%f"
PROMPT+='$(git_prompt_info)'
PROMPT+="%F{38}]%f%F{158}$%f "
ZSH_THEME_GIT_PROMPT_PREFIX=" %F{201}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY=""
ZSH_THEME_GIT_PROMPT_CLEAN=""
