. "$HOME/.cargo/env"
PATH=$HOME/bin:/usr/local/bin:$HOME/anaconda3/bin:$PATH
PATH=$HOME/Applications:$PATH
PATH=/opt/platform-tools:$PATH
PATH=/home/sandesh/.local/bin:$PATH
PATH=/home/sandesh/go/bin:$PATH
PATH=$PATH:/usr/local/go/bin
PATH=$PATH:/opt/zig/
# fnm
FNM_PATH="/home/sandesh/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  eval "`fnm env`"
fi

export PATH
